flutter_application_path = '../movie_detail_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'SimpleMovie' do
    install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
    flutter_post_install(installer) if defined?(flutter_post_install)
end